language: php
php:
  - '7.0'

install:
  - composer install --dev --no-interaction

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp tests/.travis.parameters_test.yml app/config/parameters_test.yml

script:
  - phpunit

after_success:
  - travis_retry php vendor/bin/coveralls --coverage_clover tests/clover.xml